### ISSUE TITLE
Use SQL instead of Minio

### ISSUE THREAD

**Issue by robzienert** [armory/minnaker#32]
The SQL backend is more aligned with the future direction of Spinnaker, and also supports versioning.

**Comment by robzienert** [comment]
I'm happy to knock out this work if it's agreeable.

**Comment by justinrlee** [comment]
Hey @robzienert, sorry for the late response (holidays and all).  This would be cool.  Are you thinking of just running a maridab/mysql container?  Or something more?

**Comment by robzienert** [comment]
This would just be a MySQL container, yes. Doesn't need to be anything flashy.

**Comment by aleon1220** [comment]
Hi i am in the same boat. If i stop the AWS EC2 instance the history of executed pipelines is gone. I dont want that to happen. Is it related to this Issue right?

**Comment by justinrlee** [comment]
Hey Rob - yeah, mysql container would be fantastic.  I'll see if I can knock this out this weekend or something, or you're welcome to take a whack.

@aleon1220 moving front50 to mysql instead of redis won't help with pipeline execution history.  You need a way to persist data in redis (which could be done with a local volume mount or PV, i just haven't done it yet).  That's a separate issue, I think.

**Comment by aleon1220** [comment]
> Hey Rob - yeah, mysql container would be fantastic. I'll see if I can knock this out this weekend or something, or you're welcome to take a whack.
> 
> @aleon1220 moving front50 to mysql instead of redis won't help with pipeline execution history. You need a way to persist data in redis (which could be done with a local volume mount or PV, i just haven't done it yet). That's a separate issue, I think.

oh i see. OK thanks for that. Is this issue in your road map. I am happy to describe it. and create an issue
